DROP TRIGGER IF EXISTS holdings_match_market_reservations ON inventory.holdings;
DROP TRIGGER IF EXISTS inventory_reservations_match_holding ON markets.order_reservations;
DROP TRIGGER IF EXISTS reservations_match_order ON markets.order_reservations;
DROP TRIGGER IF EXISTS orders_require_reservations ON markets.orders;
DROP TRIGGER IF EXISTS trades_match_orders ON markets.trades;
DROP TRIGGER IF EXISTS orders_match_trade_totals ON markets.orders;
DROP TRIGGER IF EXISTS trades_are_immutable ON markets.trades;
DROP TRIGGER IF EXISTS order_reservations_guard_update ON markets.order_reservations;
DROP TRIGGER IF EXISTS orders_guard_update ON markets.orders;
DROP FUNCTION IF EXISTS markets.assert_holding_reservation_total();
DROP FUNCTION IF EXISTS markets.assert_order_reservations_consistent();
DROP FUNCTION IF EXISTS markets.assert_order_fill_consistent();
DROP FUNCTION IF EXISTS markets.reject_trade_change();
DROP FUNCTION IF EXISTS markets.guard_reservation_update();
DROP FUNCTION IF EXISTS markets.guard_order_update();
DROP TABLE IF EXISTS markets.trades;
DROP TABLE IF EXISTS markets.order_reservations;
DROP TABLE IF EXISTS markets.orders;
DROP TABLE IF EXISTS markets.markets;
DROP SCHEMA IF EXISTS markets;
