// Command protocolgen creates Go and TypeScript envelope bindings from the
// repository's JSON Schema source.
package main

import (
	"bytes"
	"encoding/json"
	"errors"
	"flag"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"slices"
	"strings"
	"unicode"
)

const (
	schemaPath = "protocol/schema/envelopes.schema.json"
	goPath     = "protocol/gen/go/envelopes.gen.go"
	tsPath     = "protocol/gen/ts/envelopes.gen.ts"
)

type document struct {
	Version string            `json:"x-ascent-protocol-version"`
	Defs    map[string]schema `json:"$defs"`
}

type schema struct {
	Type                 any               `json:"type"`
	Format               string            `json:"format"`
	Ref                  string            `json:"$ref"`
	Enum                 []string          `json:"enum"`
	Required             []string          `json:"required"`
	Properties           map[string]schema `json:"properties"`
	AdditionalProperties any               `json:"additionalProperties"`
}

func main() {
	check := flag.Bool("check", false, "verify that generated files are current")
	flag.Parse()

	if err := run(*check); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

func run(check bool) error {
	raw, err := os.ReadFile(schemaPath)
	if err != nil {
		return fmt.Errorf("read protocol schema: %w", err)
	}

	var doc document
	if err := json.Unmarshal(raw, &doc); err != nil {
		return fmt.Errorf("decode protocol schema: %w", err)
	}
	if doc.Version == "" {
		return errors.New("protocol schema is missing x-ascent-protocol-version")
	}
	if len(doc.Defs) == 0 {
		return errors.New("protocol schema has no $defs")
	}

	goSource, err := generateGo(doc)
	if err != nil {
		return err
	}
	tsSource, err := generateTypeScript(doc)
	if err != nil {
		return err
	}

	outputs := map[string][]byte{
		goPath: goSource,
		tsPath: tsSource,
	}
	for path, content := range outputs {
		if check {
			current, readErr := os.ReadFile(path)
			if readErr != nil {
				return fmt.Errorf("%s is missing; run make generate", path)
			}
			if !bytes.Equal(current, content) {
				return fmt.Errorf("%s is stale; run make generate", path)
			}
			continue
		}
		if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
			return fmt.Errorf("create output directory: %w", err)
		}
		if err := os.WriteFile(path, content, 0o644); err != nil {
			return fmt.Errorf("write %s: %w", path, err)
		}
	}
	return nil
}

func generateGo(doc document) ([]byte, error) {
	var out strings.Builder
	out.WriteString("// Code generated by protocolgen; DO NOT EDIT.\n\n")
	out.WriteString("package protocol\n\n")
	out.WriteString("import (\n\t\"encoding/json\"\n\t\"time\"\n)\n\n")
	fmt.Fprintf(&out, "const Version = %q\n\n", doc.Version)

	for _, name := range sortedKeys(doc.Defs) {
		def := doc.Defs[name]
		if len(def.Enum) > 0 {
			fmt.Fprintf(&out, "type %s string\n\nconst (\n", name)
			for _, value := range def.Enum {
				fmt.Fprintf(&out, "\t%s%s %s = %q\n", name, pascal(value), name, value)
			}
			out.WriteString(")\n\n")
			continue
		}
		if firstType(def.Type) != "object" {
			return nil, fmt.Errorf("unsupported definition %s: expected object or enum", name)
		}
		fmt.Fprintf(&out, "type %s struct {\n", name)
		required := toSet(def.Required)
		for _, propertyName := range sortedKeys(def.Properties) {
			property := def.Properties[propertyName]
			goType, nullable, err := goType(property)
			if err != nil {
				return nil, fmt.Errorf("%s.%s: %w", name, propertyName, err)
			}
			optional := !required[propertyName]
			if (nullable || optional) && !strings.HasPrefix(goType, "*") {
				goType = "*" + goType
			}
			jsonTag := propertyName
			if optional {
				jsonTag += ",omitempty"
			}
			fmt.Fprintf(&out, "\t%s %s `json:%q`\n", pascal(propertyName), goType, jsonTag)
		}
		out.WriteString("}\n\n")
	}

	command := exec.Command("gofmt")
	command.Stdin = strings.NewReader(out.String())
	formatted, err := command.Output()
	if err != nil {
		return nil, fmt.Errorf("format generated Go with gofmt: %w", err)
	}
	return formatted, nil
}

func generateTypeScript(doc document) ([]byte, error) {
	var out strings.Builder
	out.WriteString("// Code generated by protocolgen; DO NOT EDIT.\n\n")
	fmt.Fprintf(&out, "export const PROTOCOL_VERSION = %q as const;\n\n", doc.Version)

	for _, name := range sortedKeys(doc.Defs) {
		def := doc.Defs[name]
		if len(def.Enum) > 0 {
			quoted := make([]string, 0, len(def.Enum))
			for _, value := range def.Enum {
				quoted = append(quoted, fmt.Sprintf("%q", value))
			}
			fmt.Fprintf(&out, "export type %s = %s;\n\n", name, strings.Join(quoted, " | "))
			continue
		}
		if firstType(def.Type) != "object" {
			return nil, fmt.Errorf("unsupported definition %s: expected object or enum", name)
		}
		fmt.Fprintf(&out, "export interface %s {\n", name)
		required := toSet(def.Required)
		for _, propertyName := range sortedKeys(def.Properties) {
			property := def.Properties[propertyName]
			tsType, nullable, err := tsType(property)
			if err != nil {
				return nil, fmt.Errorf("%s.%s: %w", name, propertyName, err)
			}
			optional := ""
			if !required[propertyName] {
				optional = "?"
			}
			if nullable {
				tsType += " | null"
			}
			fmt.Fprintf(&out, "  %s%s: %s;\n", propertyName, optional, tsType)
		}
		out.WriteString("}\n\n")
	}
	return []byte(strings.TrimRight(out.String(), "\n") + "\n"), nil
}

func goType(value schema) (string, bool, error) {
	if value.Ref != "" {
		return filepath.Base(value.Ref), false, nil
	}
	kind, nullable := normalizedType(value.Type)
	switch kind {
	case "string":
		if value.Format == "date-time" {
			return "time.Time", nullable, nil
		}
		return "string", nullable, nil
	case "integer":
		return "int64", nullable, nil
	case "number":
		return "float64", nullable, nil
	case "boolean":
		return "bool", nullable, nil
	case "object":
		return "json.RawMessage", nullable, nil
	default:
		return "", false, fmt.Errorf("unsupported schema type %q", kind)
	}
}

func tsType(value schema) (string, bool, error) {
	if value.Ref != "" {
		return filepath.Base(value.Ref), false, nil
	}
	kind, nullable := normalizedType(value.Type)
	switch kind {
	case "string":
		return "string", nullable, nil
	case "integer", "number":
		return "number", nullable, nil
	case "boolean":
		return "boolean", nullable, nil
	case "object":
		return "Record<string, unknown>", nullable, nil
	default:
		return "", false, fmt.Errorf("unsupported schema type %q", kind)
	}
}

func normalizedType(value any) (string, bool) {
	switch typed := value.(type) {
	case string:
		return typed, false
	case []any:
		types := make([]string, 0, len(typed))
		for _, item := range typed {
			if text, ok := item.(string); ok {
				types = append(types, text)
			}
		}
		nullable := slices.Contains(types, "null")
		for _, item := range types {
			if item != "null" {
				return item, nullable
			}
		}
	}
	return "", false
}

func firstType(value any) string {
	kind, _ := normalizedType(value)
	return kind
}

func pascal(value string) string {
	var out []rune
	upperNext := true
	for _, char := range value {
		if char == '_' || char == '-' || char == ' ' {
			upperNext = true
			continue
		}
		if upperNext {
			out = append(out, unicode.ToUpper(char))
			upperNext = false
			continue
		}
		out = append(out, char)
	}
	return string(out)
}

func sortedKeys[T any](values map[string]T) []string {
	keys := make([]string, 0, len(values))
	for key := range values {
		keys = append(keys, key)
	}
	slices.Sort(keys)
	return keys
}

func toSet(values []string) map[string]bool {
	result := make(map[string]bool, len(values))
	for _, value := range values {
		result[value] = true
	}
	return result
}
